-- While this script can be used for additional database 
-- level permissions for roles defined in the project,
-- it is preferred if the permissions go into the same
-- script as the role creation.
