CREATE TABLE [dbo].[stgTradeBooksImport]
(
	[PID] [decimal](12, 0) NOT NULL,
	[ISBN] [varchar](10) NULL,
	[UPC] [varchar](13) NULL,
	[MediaCode] [varchar](1) NOT NULL,
	[Title] [nvarchar](255) NOT NULL,
	[Subtitle] [nvarchar](255) NULL,
	[ItemPrice] [money] NOT NULL,
	[ItemPriceCurrency] [varchar](3) NOT NULL,
	[Discount] [tinyint] NULL,
	[PublicationDate] [datetime] NULL,
	[VendorID] [varchar](15) NOT NULL,
	[FormatBindingCode] [varchar](2) NULL,
	[PublisherID] [varchar](20) NULL,
	[RepID] [int] NULL,
	[StatusCode] [varchar](3) NOT NULL,
	[Language] [varchar](50) NULL,
	[EditionNumber] [char](5) NULL,
	[EditionDescription] [varchar](50) NULL,
	[SeriesTitle] [nvarchar](255) NULL,
	[SeriesNumber] [varchar](100) NULL,
	[VolumeNumber] [smallint] NULL,
	[NumberOfVolumes] [smallint] NULL,
	[SubjectCode1] [char](9) NULL,
	[SubjectCode2] [char](9) NULL,
	[SubjectCode3] [char](9) NULL,
	[NumberOfPages] [smallint] NULL,
	[C1FirstName] [nvarchar](50) NULL,
	[C1LastName] [nvarchar](50) NULL,
	[C1MiddleName] [nvarchar](50) NULL,
	[C1Role] [varchar](50) NULL,
	[C2FirstName] [nvarchar](50) NULL,
	[C2LastName] [nvarchar](50) NULL,
	[C2MiddleName] [nvarchar](50) NULL,
	[C2Role] [varchar](50) NULL,
	[C3FirstName] [nvarchar](50) NULL,
	[C3LastName] [nvarchar](50) NULL,
	[C3MiddleName] [nvarchar](50) NULL,
	[C3Role] [varchar](50) NULL,
	[CanadianTitle] [varchar](1) NULL,
	[AgeLowerLimit] [char](2) NULL,
	[AgeUpperLimit] [char](2) NULL,
	[GradeLowerLimit] [char](2) NULL,
	[GradeUpperLimit] [char](2) NULL,
	[AudienceCode] [varchar](3) NULL,
	[Height] [decimal](9, 4) NULL,
	[Width] [decimal](9, 4) NULL,
	[Depth] [decimal](9, 4) NULL,
	[MeasurementUnits] [char](2) NULL,
	[Weight] [decimal](9, 4) NULL,
	[WeightUnits] [char](2) NULL,
	[CartonHeight] [decimal](9, 4) NULL,
	[CartonWidth] [decimal](9, 4) NULL,
	[CartonDepth] [decimal](9, 4) NULL,
	[CartonMeasurementUnits] [char](2) NULL,
	[CartonWeight] [decimal](9, 4) NULL,
	[CartonWeightUnits] [char](2) NULL,
	[CartonQuantity] [smallint] NULL,
	[MinimumOrderQuantity] [smallint] NULL,
	[SuggestedOrderQuantity] [smallint] NULL,
	[Note] [ntext] NULL,
	[NoteType] [varchar](20) NULL,
	[PaperCertificationType] [varchar](255) NULL,
	[ChainofCustody] [varchar](255) NULL,
	[CertifiedPostConsumerWaste_PCW] [varchar](255) NULL,
	[CertifiedPCWPercentage] [varchar](255) NULL,
	[UncertifiedPCW] [varchar](255) NULL,
	[UncertifiedPCWPercentage] [varchar](255) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
