CREATE TABLE [dbo].[BowkerAwardCodes](
	[PrizeCode] [varchar](2) NOT NULL,
	[Description] [varchar](100) NULL,
 CONSTRAINT [PK_BowkerAwardCodes] PRIMARY KEY CLUSTERED 
(
	[PrizeCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
)
