CREATE TABLE [dbo].[EBookISBNRange]
(
	[ISBN] [varchar](13) NOT NULL,
	[IsUsed] [bit] NOT NULL,
 CONSTRAINT [PK_EBookISBNRange] PRIMARY KEY CLUSTERED 
(
	[ISBN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[EBookISBNRange] ADD  CONSTRAINT [DF_tbl_001_eBookISBNRange_IsUsed]  DEFAULT (0) FOR [IsUsed]
GO