CREATE TABLE [dbo].[EBookWorks](
	[PID] [decimal](12, 0) NOT NULL,
	[WorkID] [int] NOT NULL,
	[DateChanged] [datetime] NULL,
 CONSTRAINT [PK_EBookWorks] PRIMARY KEY CLUSTERED 
(
	[PID] ASC,
	[WorkID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
