
CREATE TABLE [dbo].[refDiscountType](
[ResultTypeCode] [char](1) NOT NULL,
[ResultType] [varchar](20) NOT NULL,
CONSTRAINT [PK_refDiscountType] PRIMARY KEY CLUSTERED 
(
	[ResultTypeCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON [dbo].[refDiscountType] TO [TWRExporter]
GO
