CREATE TABLE [syme].[tbl_001_ReturnFormats](
	[ReturnFormat] [CHAR](1) NOT NULL,
	[Description] [VARCHAR](50) NULL,
	[StrpCoverCode] [VARCHAR](50) NULL,
 CONSTRAINT [PK_tbl_001_FormatCodes] PRIMARY KEY CLUSTERED 
(
	[ReturnFormat] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
