CREATE TABLE [syme].[tbl_Syme_Catalog_Settings](
	[FieldType] [VARCHAR](50) NOT NULL,
	[pid] [TINYINT] NULL,
	[ISBN] [TINYINT] NULL,
	[VendorID] [TINYINT] NULL,
	[VendorName] [TINYINT] NULL,
	[Title] [TINYINT] NULL,
	[Subtitle] [TINYINT] NULL,
	[SeriesTitle] [TINYINT] NULL,
	[Contributor1Role] [TINYINT] NULL,
	[Contributor1LastName] [TINYINT] NULL,
	[Contributor1FirstName] [TINYINT] NULL,
	[Contributor1InitialMiddleName] [TINYINT] NULL,
	[Contributor2Role] [TINYINT] NULL,
	[Contributor2LastName] [TINYINT] NULL,
	[Contributor2FirstName] [TINYINT] NULL,
	[Contributor2InitialMiddleName] [TINYINT] NULL,
	[Contributor3Role] [TINYINT] NULL,
	[Contributor3LastName] [TINYINT] NULL,
	[Contributor3FirstName] [TINYINT] NULL,
	[Contributor3InitialMiddleName] [TINYINT] NULL,
	[Media] [TINYINT] NULL,
	[Binding] [TINYINT] NULL,
	[ItemPrice] [TINYINT] NULL,
	[ItemPriceCurrency] [TINYINT] NULL,
	[Discount] [TINYINT] NULL,
	[PubDate] [TINYINT] NULL,
	[StatusCode] [TINYINT] NULL,
	[PublisherID] [TINYINT] NULL,
	[BisacSubjectCode1] [TINYINT] NULL,
	[BisacSubjectCode2] [TINYINT] NULL,
	[BisacSubjectCode3] [TINYINT] NULL,
	[SuggestedBuy] [TINYINT] NULL,
	[PrintQuantity] [TINYINT] NULL,
	[OLDISBN] [TINYINT] NULL,
	[OLDISBNOutofPrintDate] [TINYINT] NULL,
	[EditionNumber] [TINYINT] NULL,
	[EditionDescription] [TINYINT] NULL,
	[VolumeNumber] [TINYINT] NULL,
	[NumberofVolumes] [TINYINT] NULL,
	[NumberofPages] [TINYINT] NULL,
	[Height] [TINYINT] NULL,
	[Width] [TINYINT] NULL,
	[Depth] [TINYINT] NULL,
	[MeasurementUnits] [TINYINT] NULL,
	[Weight] [TINYINT] NULL,
	[WeightUnits] [TINYINT] NULL,
	[CartonQuantity] [TINYINT] NULL,
	[MinimumOrderQuantity] [TINYINT] NULL,
	[CanadianTitle] [TINYINT] NULL,
	[AudienceCode] [TINYINT] NULL,
	[GradeLowerLimit] [TINYINT] NULL,
	[GradeUpperLimit] [TINYINT] NULL,
	[AgeLowerLimit] [TINYINT] NULL,
	[AgeUpperLimit] [TINYINT] NULL,
	[Language] [TINYINT] NULL,
	[FileName] [TINYINT] NULL,
	[Catalogue Name] [TINYINT] NULL,
	[Catalogue Page Number] [TINYINT] NULL,
	[CatalogueName] [TINYINT] NULL,
	[CataloguePageNumber] [TINYINT] NULL,
	[ReturnFormat] [TINYINT] NULL,
 CONSTRAINT [PK_tbl_Syme_Catalog_Settings] PRIMARY KEY CLUSTERED 
(
	[FieldType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
