CREATE TABLE [syme].[tblUser](
	[UserID] [INT] IDENTITY(1,1) NOT NULL,
	[UserName] [VARCHAR](20) NOT NULL,
	[Password] [VARCHAR](20) NOT NULL,
	[VendorID] [VARCHAR](50) NOT NULL,
	[VendorName] [VARCHAR](80) NOT NULL,
	[IsDisabled] [TINYINT] NOT NULL,
 CONSTRAINT [PK_tblUsers] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [syme].[tblUser] ADD  CONSTRAINT [tblUser_DF_IsDisabled]  DEFAULT (0) FOR [IsDisabled]
GO