CREATE TABLE [syme].[tblUserSession](
	[GUID] [CHAR](32) NOT NULL,
	[LastUpdated] [DATETIME] NOT NULL,
	[UserID] [INT] NOT NULL,
 CONSTRAINT [PK_tblUserSession] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [syme].[tblUserSession]  WITH NOCHECK ADD  CONSTRAINT [FK_tblUserSession_tblUser1] FOREIGN KEY([UserID])
REFERENCES [syme].[tblUser] ([UserID])
GO

ALTER TABLE [syme].[tblUserSession] CHECK CONSTRAINT [FK_tblUserSession_tblUser1]
GO