CREATE TABLE [dbo].[TWRDiscounts](
[Id] [INT] IDENTITY(1,1) NOT NULL,
[PricingId] [INT] NOT NULL,
[ResultType] [CHAR](1) NOT NULL,
[ResultValue] [DECIMAL](9, 5) NOT NULL,
[IsEnabled] [BIT] NOT NULL,
CONSTRAINT [PK_TWRDiscounts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC,
	[PricingId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON [dbo].[TWRDiscounts] TO [TWRExporter]
GO
