CREATE TABLE [dbo].[TWRPricing](
[Id] [int] IDENTITY(1,1) NOT NULL,
[Name] [varchar](16) NOT NULL,
[Description] [varchar](255) NULL,
[TWRLevel] [varchar](16) NOT NULL,
[IsEnabled] [bit] NOT NULL,
 CONSTRAINT [PK_TWRPricing] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON dbo.TWRPricing TO [TWRExporter]
GO
