IF OBJECT_ID('tempdb..[#refMerchandiseCategories]') IS NOT NULL DROP TABLE [#refMerchandiseCategories];

CREATE TABLE [#refMerchandiseCategories]
(
	[MerchCategoryId] varchar(10) NOT NULL
,	[Description] nvarchar(MAX) NULL
,	[VisibleToCart] bit NOT NULL
);

INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('F10101', '{"en":"FINANCE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('F10102', '{"en":"GIFT CARDS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('F10103', '{"en":"CREDIT NOTES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('F10105', '{"en":"(DO NOT USE) RYERSON BOOKSTORE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10101', '{"en":"LICENSED PRODUCT","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10102', '{"en":"CHOCOLATE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10103', '{"en":"HOME ACCENTS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10104', '{"en":"FITNESS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10105', '{"en":"PLUSH","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10106', '{"en":"GAMES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10107', '{"en":"SCENTS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10108', '{"en":"ACCESSORIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10109', '{"en":"GARDEN","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10110', '{"en":"BABY & KIDS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10111', '{"en":"FOOD & COOKING","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10112', '{"en":"IMPULSE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10120', '{"en":"DNU LIFESTYLES STRAT","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10121', '{"en":"DNU HOME FURNISHINGS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10122', '{"en":"GLASSWARE & BAR","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10123', '{"en":"CANDY CONFECTIONS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10124', '{"en":"GAMES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10125', '{"en":"DO NOT USE HOME OFFICE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10126', '{"en":"WELLNESS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10127', '{"en":"SCARVES & COLD WEATHER","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10128', '{"en":"PLUSH","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10129', '{"en":"HOME FRAGRANCE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10130', '{"en":"LOVE OF READING GIFT","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10131', '{"en":"DNU TRAVEL SHOP","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10132', '{"en":"GIFT PRODUCTS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10133', '{"en":"MUGS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10134', '{"en":"BAGS & TOTES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10135', '{"en":"DO NOT USE GARDEN & OUTDOOR","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10136', '{"en":"ON THE GO","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10137', '{"en":"GODIVA","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10138', '{"en":"WALL DECOR","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10139', '{"en":"(DO NOT USE) THE STUDY","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10140', '{"en":"(DO NOT USE) KOBO ACCESSORIES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10141', '{"en":"DINNERWARE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10142', '{"en":"SERVEWARE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10143', '{"en":"TABLE LINENS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10144', '{"en":"NOVELTY GIFTS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10145', '{"en":"TEA & COFFEE ACCESSORIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10146', '{"en":"CHOCOLATE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10147', '{"en":"GOURMET GIFTS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10148', '{"en":"SPECIALTY TEA & SEASONAL BEVERAGES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10149', '{"en":"SNACKS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10150', '{"en":"NOVELTY SEASONAL","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10151', '{"en":"PILLOWS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10152', '{"en":"HOME ACCENTS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10153', '{"en":"DO NOT USE BASKETS & ORGANIZATION","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10154', '{"en":"SEASONAL DECOR","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10155', '{"en":"READING COZIES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10156', '{"en":"BODY CARE & FRAGRANCE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10157', '{"en":"KEEPSAKES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10158', '{"en":"DEVELOPMENT GIFTS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10159', '{"en":"BABY CLOSET","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10160', '{"en":"SLEEP SHOP","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10161', '{"en":"BATH SHOP","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10162', '{"en":"SMALL ACCESSORIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10163', '{"en":"THROWS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10164', '{"en":"HYDRATION","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10165', '{"en":"COFFEE ACCESSORIES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10166', '{"en":"POUCHES & WALLETS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10167', '{"en":"READING GLASSES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10190', '{"en":"PWP LIFESTYLE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10191', '{"en":"IREUSE BAGS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10198', '{"en":"","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10199', '{"en":"GIFT INACTIVE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10201', '{"en":"PAPYRUS GREETING CARDS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10202', '{"en":"SOCIAL STATIONERY","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10203', '{"en":"READING ACCESSORIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10204', '{"en":"JOURNALS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10205', '{"en":"GIFT BOOKS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10206', '{"en":"PAPER DUMP BIN","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10207', '{"en":"AGENDAS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10208', '{"en":"NOVELTY","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10209', '{"en":"TRAVEL SHOP","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10210', '{"en":"BAGS & TOTES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10211', '{"en":"PARTY SHOP","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10212', '{"en":"ALBUMS & RECIPES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10213', '{"en":"DISCONTINUED STATIONARY","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10214', '{"en":"THE STUDY","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10215', '{"en":"PHOTOSHOP","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10216', '{"en":"VMI SPINNER","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10217', '{"en":"VMI BOOKMARK","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10218', '{"en":"GREETING CARDS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10219', '{"en":"PAPYRUS PARTY SHOP","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10220', '{"en":"VMI READERS & ACCESSORIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10221', '{"en":"E-READING ACCESSORIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10222', '{"en":"NOVELTY STATIONERY","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10223', '{"en":"WRITING","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10224', '{"en":"DESKTOP","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10225', '{"en":"GUIDED JOURNALS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10226', '{"en":"COLOURING INSTRUMENTS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10227', '{"en":"CALENDARS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10230', '{"en":"LOVE OF READING PAPER","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10231', '{"en":"PROMOTIONS PAPER","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10232', '{"en":"DNU PAPER STRAT","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10298', '{"en":"","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10299', '{"en":"PAPER INACTIVE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10301', '{"en":"WHOLESALE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10302', '{"en":"LOR GIFTCARD HOLDERS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10303', '{"en":"PROMOTIONAL ITEMS PWP","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10304', '{"en":"DO NOT USE PURCHASE WITH PURCHASE PAPER","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10305', '{"en":"SAMBA DAYS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10306', '{"en":"ITUNES GIFT CARDS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10307', '{"en":"KOBO GIFT CARDS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10400', '{"en":"DO NOT USE - TOY & BABY STRAT","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10401', '{"en":"PLUSH","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10402', '{"en":"KEEPSAKES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10403', '{"en":"DEVELOPMENT GIFTS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10404', '{"en":"BABY CLOSET","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10405', '{"en":"SLEEP SHOP","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10406', '{"en":"BATHSHOP","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10407', '{"en":"TODDLER","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10408', '{"en":"MELISSA & DOUG","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10409', '{"en":"MAKE BELIEVE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10410', '{"en":"SCIENCE & DISCOVERY","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10411', '{"en":"THOMAS & FRIENDS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10412', '{"en":"PLANES TRAINS & AUTOMOBILES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10413', '{"en":"SPORTS & ACTIVITIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10414', '{"en":"ARTS & CRAFTS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10415', '{"en":"DOLLS & PLUSH","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10416', '{"en":"ROOM DECOR & ACCESSORIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10417', '{"en":"AMERICAN GIRL","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10418', '{"en":"AMERICAN GIRL SERVICES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10419', '{"en":"LEGO","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10420', '{"en":"GAMES & PUZZLES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10421', '{"en":"IMPULSE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10422', '{"en":"KIDS LIFESTYLE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10423', '{"en":"LICENSE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10499', '{"en":"TOY & BABY INACTIVE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10501', '{"en":"CORE ACCESSORIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10502', '{"en":"APPLE HARDWARE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10503', '{"en":"APPLE ACCESSORIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10504', '{"en":"PASSIONS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10505', '{"en":"PROTECTION","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10506', '{"en":"AUDIO","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10507', '{"en":"KOBO HARDWARE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10508', '{"en":"KOBO ACCESSORIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10509', '{"en":"KIDS TECH & VIDEO GAMES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10599', '{"en":"ELECTRONICS INACTIVE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('G10701', '{"en":"CALENDARS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10101', '{"en":"MUSIC","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10103', '{"en":"KARAOKE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10104', '{"en":"SUPER AUDIO","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10105', '{"en":"POP \/ ROCK","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10106', '{"en":"ELECTRONICA \/ DANCE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10107', '{"en":"R&B \/ SOUL","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10108', '{"en":"BLUES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10109', '{"en":"FOLK","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10110', '{"en":"COUNTRY","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10111', '{"en":"JAZZ","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10112', '{"en":"CLASSICAL","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10113', '{"en":"NEW AGE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10114', '{"en":"GOSPEL \/ RELIGIOUS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10115', '{"en":"WORLD","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10116', '{"en":"SOUNDTRACK","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10117', '{"en":"KIDS MUSIC","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10118', '{"en":"VALUE MUSIC","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10119', '{"en":"BRANDED","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10198', '{"en":"MUSIC CONSIGNMENT","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10201', '{"en":"DVD","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10202', '{"en":"VIDEO","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10203', '{"en":"MUSIC DVD","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10204', '{"en":"MOVIES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10205', '{"en":"TV","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10206', '{"en":"SPECIAL INTEREST","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10207', '{"en":"HEALTH","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10208', '{"en":"KIDS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10209', '{"en":"ANIME","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10210', '{"en":"MUSIC VIDEO","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10211', '{"en":"VALUE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10212', '{"en":"BLU RAY MOVIES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10301', '{"en":"MULTIMEDIA","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10302', '{"en":"BRANDED GROCERY","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10303', '{"en":"KOBO","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10304', '{"en":"CORE ACCESSORIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10305', '{"en":"DNU WARRANTIES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10306', '{"en":"HEALTH & FITNESS TECH","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10307', '{"en":"VIDEO GAMES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10308', '{"en":"KOBO ACCESSORIES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10309', '{"en":"PROTECTION","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10310', '{"en":"APPLE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10311', '{"en":"AUDIO ELECTRONICS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10312', '{"en":"APPLE ACCESSORIES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10313', '{"en":"LIFESTYLE TECH","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('M10314', '{"en":"KIDS TECH","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10100', '{"en":"DO NOT USE - TRADE STRAT","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10101', '{"en":"BIOGRAPHY","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10102', '{"en":"COMMUNITY & CULTURE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10103', '{"en":"HISTORY & POLITICAL SCIENCE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10104', '{"en":"DNU LITERARY CRITICISM","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10105', '{"en":"PHILOSOPHY","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10106', '{"en":"ARTS & LETTERS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10107', '{"en":"RELIGION","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10109', '{"en":"SOFTWARE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10110', '{"en":"BUSINESS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10111', '{"en":"COMPUTERS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10112', '{"en":"LANGUAGE AND DICTIONARIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10113', '{"en":"MAP BOOKS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10114', '{"en":"MAPS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10115', '{"en":"PETS & ANIMALS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10116', '{"en":"REFERENCE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10117', '{"en":"SCIENCE & NATURE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10118', '{"en":"DNU TRANSPORTATION","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10120', '{"en":"GAMES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10121', '{"en":"HUMOUR","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10122', '{"en":"MUSIC & PERFORMING ARTS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10123', '{"en":"SPORTS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10124', '{"en":"TRUE CRIME","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10140', '{"en":"FICTION & LITERATURE TP\/HC","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10141', '{"en":"LARGE PRINT","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10142', '{"en":"MYSTERY TP & HC","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10143', '{"en":"ROMANCE TP & HC","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10144', '{"en":"SCIENCE FICTION & FANTASY TP\/HC","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10145', '{"en":"AUDIO","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10146', '{"en":"FICTION & LITERATURE MASS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10147', '{"en":"MYSTERY MASS MARKET","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10148', '{"en":"ROMANCE MASS MARKET","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10149', '{"en":"SCIENCE FICTION & FANTASY MASS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10150', '{"en":"ACTIVITY BKS - ALL AGES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10151', '{"en":"BABIES & TODDLERS AGES 0-2","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10152', '{"en":"CHAPTER BOOKS AGES 6-8","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10153', '{"en":"HOLIDAYS & CELBRATIONS - ALL AGES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10154', '{"en":"KIDS REFERENCE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10155', '{"en":"STORYTIME AGES 3-5","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10156', '{"en":"TEENS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10157', '{"en":"YOUNG READERS AGES 9-12","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10158', '{"en":"TEACHING RESOURCES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10159', '{"en":"PARENTING","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10160', '{"en":"TOYS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10161', '{"en":"DO NOT USE ROSETTA STONE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10167', '{"en":"FASHION","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10168', '{"en":"LIFESTYLE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10169', '{"en":"ANTIQUES & COLLECTIBLES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10170', '{"en":"ART","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10171', '{"en":"COOKING","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10172', '{"en":"CRAFTS & HOBBIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10173', '{"en":"GARDENING","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10174', '{"en":"WELL BEING","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10175', '{"en":"THE HOME","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10176', '{"en":"NEW AGE & OCCULT","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10177', '{"en":"PHOTOGRAPHY","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10178', '{"en":"HEALTH","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10179', '{"en":"TRAVEL","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10180', '{"en":"LITTLE BKS & MINI KITS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10181', '{"en":"MANGA","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10182', '{"en":"GRAPHIC NOVELS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10183', '{"en":"COLES NOTES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10184', '{"en":"ADULT COLOURING BOOKS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10185', '{"en":"LOCAL INTEREST","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10190', '{"en":"TOYS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10191', '{"en":"KIDS ELECTRONICS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10197', '{"en":"RYERSON BOOKSTORE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10198', '{"en":"CONSIGNMENT","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10199', '{"en":"CLEARANCE  & CYBER","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10201', '{"en":"BARGAIN NON FICTION REMAINDERS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10202', '{"en":"BARGAIN BUSINESS & REFERENCE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10203', '{"en":"BARGAIN ENTERTAINMENT","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10204', '{"en":"BARGAIN FICTION REMAINDERS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10205', '{"en":"BARGAIN KIDS REM","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10206', '{"en":"BARGAIN LIFESTYLE REMAINDERS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10207', '{"en":"DO NOT USE BARGAIN STRAT","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10208', '{"en":"BARGAIN NON FICTION PACKAGES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10209', '{"en":"BAR. BUS & REF PKG","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10210', '{"en":"BAR. ENTERTAIN. PKG","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10211', '{"en":"BARGAIN FICTION PACKAGES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10212', '{"en":"BARGAIN KIDS PACKAGES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10213', '{"en":"BARGAIN LIFESTYLE PACKAGES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10214', '{"en":"BAR. FINDS PKG.","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10215', '{"en":"BARGAIN CANADIANA","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10216', '{"en":"BARGAIN HISTORY","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10217', '{"en":"BAR. GAMES & HUMOUR","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10218', '{"en":"BARGAIN TEENS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10219', '{"en":"ADULT COLOURING (B)","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10220', '{"en":"BARGAIN FOOD & DRINK","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10221', '{"en":"BAR. CANADIANA PKG","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10222', '{"en":"BARGAIN HISTORY PKG","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10223', '{"en":"BAR. GAMES& HUM. PKG","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10224', '{"en":"BARGAIN TEENS PKG","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10225', '{"en":"BARGAIN ART PKG","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10226', '{"en":"BAR. FOOD &DRINK PKG","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10299', '{"en":"","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10301', '{"en":"MAGAZINES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10302', '{"en":"NEWSPAPERS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10401', '{"en":"CALENDARS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10402', '{"en":"POSTERS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10403', '{"en":"BOX CALENDARS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10404', '{"en":"MINI CALENDARS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10405', '{"en":"ENGAGEMENT CALENDARS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10498', '{"en":"CALENDAR CONSIGNMENT","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10501', '{"en":"DO NOT USE TOYS STRAT","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10510', '{"en":"DO NOT USE TOYS 1","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10511', '{"en":"ELECTRONIC TOYS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10512', '{"en":"DO NOT USE TOYS 2","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10513', '{"en":"THINGS THAT GO","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10514', '{"en":"LEGO","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10515', '{"en":"MELISSA & DOUG","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10516', '{"en":"GAMES & PUZZLES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10517', '{"en":"CREATIVITY","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10518', '{"en":"IMPULSE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10519', '{"en":"IMAGINATIVE PLAY","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10520', '{"en":"BABY & TODDLER","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10521', '{"en":"AMERICAN GIRL","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10522', '{"en":"AMERICAN GIRL SERVICES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10530', '{"en":"ARTS & CRAFTS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10531', '{"en":"CLASSIC & RETRO","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10532', '{"en":"PLUSH & DOLLS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10534', '{"en":"MAKE BELIEVE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10536', '{"en":"ROOM DECOR & ACCESSORIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10537', '{"en":"SCIENCE & DISCOVERY","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10538', '{"en":"SPORTS & ACTIVITIES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10539', '{"en":"THOMAS & FRIENDS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10540', '{"en":"PLANES TRAINS & AUTOMOBILES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10600', '{"en":"BIOGRAPHIE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10601', '{"en":"SCIENCES HUMAINES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10602', '{"en":"LOISIRS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10603', '{"en":"LITTERATURE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10604', '{"en":"JEUNESSE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10605', '{"en":"MODES DE VIE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10606', '{"en":"DNU SOLDES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10607', '{"en":"PAPETERIE","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10610', '{"en":"LANGUES ET DICTIONNAIRES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10611', '{"en":"AFFAIRES ET REFERENCE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10620', '{"en":"BEAUX ARTS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10621', '{"en":"LOISIRS ET BRICOLAGE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10622', '{"en":"SCIENCES ET NATURE (FR)","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10630', '{"en":"LITTERATURE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10631', '{"en":"LITTERATURE QUEBECOISE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10632', '{"en":"ROMANS POLICIER","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10633', '{"en":"FANTASTIQUE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10640', '{"en":"JEUNESSE ACTIVITES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10641', '{"en":"JEUNESSE REFERENCE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10642', '{"en":"PETITE ENFANCE 0-2 ANS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10643', '{"en":"PRESCOLAIRE 3-5 ANS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10644', '{"en":"JEUNES LECTEURS 6-8 ANS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10645', '{"en":"JEUNES LECTEURS 9-12 ANS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10646', '{"en":"ADOLESCENTS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10647', '{"en":"BANDES DESSINEES ET MANGAS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10650', '{"en":"ARTS DIVINATOIRES ET NOUVEL AGE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10651', '{"en":"CUISINE ET BOISSONS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10652', '{"en":"PSYCHOLOGIE ET SEXUALITE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10653', '{"en":"SANTE ET FORME PHYSIQUE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10654', '{"en":"TOURISME","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10660', '{"en":"SOLDES","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10670', '{"en":"PAPETERIE","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10701', '{"en":"ITUNES GIFTCARDS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('P10702', '{"en":"KOBO GIFTCARDS","fr":""}', 1);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('Z10101', '{"en":"STORE SUPPLIES","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('Z10102', '{"en":"LOYALTY","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('Z10103', '{"en":"LOYALTY POINTS","fr":""}', 0);
INSERT [#refMerchandiseCategories]([MerchCategoryId], [Description], [VisibleToCart]) VALUES('Z10201', '{"en":"GIFT CERTIFICATES","fr":""}', 0);

DELETE	dst
FROM	[dbo].[refMerchandiseCategories] dst
	LEFT JOIN [#refMerchandiseCategories] src ON dst.[MerchCategoryId] = src.[MerchCategoryId]
WHERE	src.[MerchCategoryId] IS NULL;

UPDATE	dst
SET	[Description] = src.[Description]
,	[VisibleToCart] = src.[VisibleToCart]
FROM	[dbo].[refMerchandiseCategories] dst
JOIN	[#refMerchandiseCategories] src ON dst.[MerchCategoryId] = src.[MerchCategoryId]
WHERE	(src.[Description] IS NULL AND dst.[Description] IS NOT NULL) OR (src.[Description] IS NOT NULL AND dst.[Description] IS NULL) OR src.[Description] <> dst.[Description]
OR	src.[VisibleToCart] <> dst.[VisibleToCart];

INSERT	[dbo].[refMerchandiseCategories] (
	[MerchCategoryId], [Description], [VisibleToCart]
)
SELECT	src.[MerchCategoryId], src.[Description], src.[VisibleToCart]
FROM	[#refMerchandiseCategories] src
	LEFT JOIN [dbo].[refMerchandiseCategories] dst ON dst.[MerchCategoryId] = src.[MerchCategoryId]
WHERE	dst.[MerchCategoryId] IS NULL;

