/*
	This script is not used for Production. It is used to set up DEV (or local)
	by using both the VSR and non-VSR table and the import stored procedure.
*/

IF OBJECT_ID('tempdb..[#stgTradeVendorsVSR]') IS NOT NULL DROP TABLE [#stgTradeVendorsVSR];

CREATE TABLE [#stgTradeVendorsVSR]
(
	[SAPVendorId] varchar(12) NOT NULL
,	[VSRCode] varchar(12) NOT NULL
,	[VSRDescription] varchar(50) NOT NULL
);

INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('700008', 'HOUNSL', 'Hounslow Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('700099', 'KLUWER', 'KLUWER ACADEMIC PUB');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('700400', '60', 'Serials');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('700400', '61', 'Non Serials');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('700400', '62', 'MRW');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('700400', '65', 'Trade');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('700400', '69', 'Textbooks');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('700477', 'KRAUSE', 'Krause Publications');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('700719', 'VINLND', 'Vinland Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'AMP', 'AMP');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'AMPGFT', 'Andrews&McMeel Gift');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'AMPPRT', 'Andrews&McMeel Print');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'ANMCGT', 'Andrews & McMeel Gft');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'APPLES', 'Applesauce Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'ATRIA', 'Atria');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'BAEN', 'Baen');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'BASEB', 'Baseball America');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'BOOM', 'Boom');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'CARDOZ', 'Cardoza');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'CHICK', 'Chicken Soup');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'CIDERM', 'Cider Mill Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'COVEY', 'Covey');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'DOWN', 'Downtown Bookworks');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'FOLGER', 'Folgers Gift');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'FREE', 'Free Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'GAMES', 'Games Workshop');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'HARL', 'Harlequin');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'KAPLAN', 'Kaplan');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'MANH', 'Manhattan GMAT');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'MEADO', 'Meadowbrook');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'MERCK', 'Merck');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'NATGEO', 'National Geographic');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'OPEN', 'Open Road');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'POCKET', 'Pocket');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'READ', 'Reader''s Digest');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'REBEL', 'Rebellion');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'RIPLEY', 'Ripley');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'S&S', 'S&S Australia');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'S&SGFT', 'S&S Gift');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'TRAVEL', 'Traveller');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'VIZ', 'Viz');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701130', 'WELDON', 'Weldon Owen');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701191', 'ACADEM', 'Remise Academique');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701199', 'SSP', 'Stepping Stone Pub');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701208', 'BEACON', 'Beacon Dist');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701247', 'LORMER', 'James Lorimer');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701251', 'BRINDL', 'Brindle & Glass Publ');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701251', 'OOLCHN', 'Oolichan Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701251', 'ROKMTN', 'Rocky Mountain Bks');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701281', 'COGUID', 'Collectors Guide Pub');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'CMHC', 'Canada Mortgage And');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'CREHOM', 'Creative Homeowners');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'CRWPUB', 'CRW Publishing Ltd');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'DALINT', 'Dalmatina/Intervisua');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'DALMAT', 'Dalmatian Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'DALPRE', 'Dalmation Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'DISNEY', 'Disney Publishing Wo');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'HANLEY', 'Hanley Wood');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'HOMTIM', 'Hometime Video Publi');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'HYPER', 'Hyperion Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'IDEALS', 'Ideals Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'KANEMI', 'Kane/Miller');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'KPORT', 'Key Porter');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'LEIART', 'Leisure Arts');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'LESEDI', 'Les Edition Heritage');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'LITBRN', 'Little Brown & Co');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'MACMIL', 'Macmillan USA');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'MARRIC', 'Marianne Richmond');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'MCRSFT', 'Microsoft Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'MEDITA', 'Meditainment Ltd.');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'MEDPRE', 'Medallion Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'MOTORB', 'Motorbooks Internati');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'NBMPUB', 'NBM PUBLISHING');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'PANMAC', 'Pan Macmillan Limite');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'PENTON', 'Penton Overseas');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'PHAIDN', 'Phaidon Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'PSKNIG', 'P.S. Knight');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'RAPIDO', 'Rapido Trains Inc.');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'RODALE', 'Rodale Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'SCHOOL', 'School Zone');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'SEQUOI', 'Sequoia Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'SLEBEA', 'Sleeping Bear');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'SOMERV', 'Sommerville - KP TR');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'SOUNDP', 'Soundprints');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'TIMHOM', 'Time Inc. Home Enter');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'WARNER', 'Warner Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'YANKEE', 'Yankee Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701324', 'ZAGAT', 'Zagat');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701334', 'SOLDES', 'SOLDES');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701342', 'APPLE', 'Apple Pub');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701342', 'IRWIN', 'Irwin Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701342', 'MUSSON', 'Musson Pub');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701342', 'POLSTR', 'Polestar');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701342', 'WARWCK', 'Warwick Pub');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701594', 'POTTER', 'Pottersfield Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701650', 'GODINE', 'David R. Godine');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('701998', 'ARCH', 'Archambault Musique');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702014', 'PGD', 'PGD');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702015', 'BMGIMP', 'BMG Special Imports');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'ACCOMO', 'Accomodating Kitchen');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'ARE', 'A.R.E. Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'ATLAS', 'ATLAS BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'BANFAL', 'Elizabeth Banfalvi');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'BKMS', 'Booksmasters');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'COURSE', 'Course in Miracles S');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'CREATI', 'Creative Art Service');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'DAWN', 'Take Heart Publicati');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'ENLIGH', 'Enlighten Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'ILLART', 'Illumination Arts Pu');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'LUCIS', 'Lucis Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'ORANGE', 'Orange Palm and Magn');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'RCP', 'Ringing Cedars Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'STEP', 'Stepping Stone Publi');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'STONE', 'Stoneworks');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'STREAM', 'Stream Entertainment');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'STRUE', 'Sounds True');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'TALK', 'Talk Enterprises');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'TOM', 'Tom Kenyon');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('702854', 'TREA', 'Treasures Of The Hea');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'ABBE', 'Abbeville Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'ACORN', 'Acorn Alliance');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'ALLIAN', 'Alliance Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'ARGO', 'Argo Navis');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'ASSLNE', 'Assouline');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'AUDIOG', 'AudioGO');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'AVEDIT', 'Avedition Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'BBCAUD', 'BBC AUDIO');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'BELLA', 'Bella Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'BLKBK', 'Black Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'BLKDOG', 'Black Dog');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'BONDI', 'Bondi');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'BOOMST', 'BOOM STUDIO');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'BOWTIE', 'Bowtie Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'BRIGHT', 'Brighter Minds');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'BURLY', 'BurlyMan Ent. Inc.');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'CAL', 'CALIFORNIA UNIV');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'CAMBIT', 'CAMBIT');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'CDNWAR', 'Canadian Bk Warwick');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'CHMERA', 'Chimera Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'CLYDES', 'Clydesdale Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'COLUMB', 'COLUMBIA UNIVERSITY');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'CONSOR', 'Consortium Book');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'CROSSG', 'Crossgeneration Cmic');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'DAP', 'D.A.P.');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'DELANO', 'Delano Greenidge');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'DESIGN', 'Design Studio Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'EASTON', 'Easton Studio Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'EDIZIO', 'Edizioni');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'EMMIS', 'Emmis Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'ENCOUR', 'Encouragement Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'FIREBB', 'Firebrand Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'FOODFB', 'Foodfirst Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'GRYCOR', 'Greycore Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'HARVBU', 'HARVARD BUSINESS SCH');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'HILLSP', 'Hill Street Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'HNDYLG', 'Handy Logic');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'HOBER', 'Hoberman Collections');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'INNOVA', 'Innova');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'KEENSP', 'Keenspot Entertainme');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'KENNEL', 'Kennel Club');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'KISSPP', 'Kissena Park Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'LEGO', 'Lego');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'LIFETM', 'LIFETIME MEDIA');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'MAGICC', 'Magic Carpet Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'MERREL', 'Merrell');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'MEYMER', 'Myer & Myer Verlag');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'MINT', 'Mint');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'MONUME', 'Monumentus Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'MOYERB', 'Moyer Bell');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'NEWMKT', 'Newmarket Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'PCTREA', 'PC TREASURES');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'PEAR', 'Pear Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'PEARSV', 'Pearson Venture Grou');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'PERSEU', 'Perseus Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'PLANET', 'Planeta');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'POWERH', 'Powerhouse');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'PRINCT', 'PRINCETON UNIV');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'PVG', 'PVG');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'RBCDRA', 'RBC Dain Rauscher');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'REGNPU', 'Regnery Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'REVOLU', 'Revolution Publishin');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'RICHP', 'Rich Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'RIPLEY', 'Ripley Entertainment');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'RIVERD', '"Riverdeep, Inc."');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'SENSEI', 'Sensei Publications');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'SFLIFE', 'Skills for Life LLC');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'SIRIUS', 'Sirius Entertainment');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'STORYP', 'The Story Plant');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'TASCHN', 'TASCHEN AMERICA');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'TITAN', 'Titan Pub');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'TOKYOP', 'Tokyopop');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'UMICH', 'UNIV OF MICHIGAN PRE');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'VIRGIN', 'Virgin Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'WATERS', 'Waterside Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('703305', 'WYATTM', 'Wyatt-Mackenzie Pub');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('704082', 'DATGFT', 'Dateworks Gift');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('704131', '10', 'discount 10');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('704131', '15', 'discount 15');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('704131', '20', 'discount 20');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('704131', '30', 'discount 30');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('704131', '40', 'discount 40');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('704131', '44', 'discount 44');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('704675', 'MGM', 'MGM');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('704747', 'HARUNV', 'Harvard Univ Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('704747', 'MIT', 'MIT Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('704747', 'YALUNV', 'Yale Univ Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705051', 'PAUPBK', 'Peter Pauper Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705099', 'CANNON', 'Cannon Book Dist');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705106', 'PEPIN', 'PEPIN PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'ARBEIT', 'ARBEITER RING PUB');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'BANFF', 'BANFF CENTRE PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'BARAKA', 'BARAKA BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'BAYEUX', 'BAYEUX ARTS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'BEACH', 'BEACH HOLME');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'BIBLIO', 'BIBLIOASIS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'BKLAND', 'BOOKLAND PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'BKTHUG', 'BOOKTHUG');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'BLKMSS', 'BLACK MOSS PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'BRICK', 'BRICK BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'BRINDL', 'BRINDLE AND GLASS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'BROKEN', 'BROKEN JAW PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'BUSCHE', 'BUSCHEK BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'CHAUDI', 'CHAUDIERE BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'COACH', 'COACH HOUSE BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'CONUND', 'CONUNDRUM PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'CUMULU', 'CUMULUS PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'DC', 'DC BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'FREEHD', 'FREEHAND BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'GUTTER', 'GUTTER PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'HAGIOS', 'HAGIOS PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'INANNA', 'INANNA PUBLICATIONS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'INSOMN', 'INSOMNIAC PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'INVISI', 'INVISIBLE PUBLISHING');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'KEGEDO', 'KEGEDONCE PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'LINDAL', 'Linda Leith Publishi');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'MANSFI', 'MANSFIELD PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'MERCUR', 'MERCURY PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'MOTHTO', 'MOTHER TONGUE PUB');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'NEWEST', 'NEWEST PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'NEWSTA', 'New Star Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'NOWNVR', 'NOW OR NEVER PUB');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'PALIMP', 'PALIMPSEST PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'PEDLAR', 'PEDLAR PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'POWPOW', 'POW POW PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'QUATTR', 'QUATTRO BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'RONSDA', 'RONSDALE OPRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'SCRVNR', 'YOUR SCRIVENER PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'SIGNAT', 'SIGNATURE EDITIONS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'SNARE', 'SNARE BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'STONEH', 'Stonehouse Publishin');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'THISLE', 'THISTLEDOWN PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'THREE', 'THREE O CLOCK PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'TIGHTR', 'TIGHTROPE BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'TSAR', 'TSAR PUBLICATIONS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'TURNST', 'TURNSTONE');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'VARCRO', 'VARIETY CROSSING PRE');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'VEHICU', 'VEHICULE PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'WINGAT', 'WINGATE PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'WKHORS', 'The Workhorsery');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'WOLSAK', 'WOLSAK AND WYNN');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'YYZBK', 'YYZBOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705254', 'ZEPHYR', 'ZEPHYR PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705332', 'DVRBRG', 'Dover Bargain');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705356', 'WORDW', 'Wordware Pub');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705412', 'ATRIUM', 'Atrium Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705412', 'TITUS', 'Titan US');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705872', 'NEWSOC', 'INACTIVE');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705872', 'PGC', 'inactive');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705872', 'PGW', 'Publishers Group Can');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705872', 'REDDR', 'Red Deer Collg Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705872', 'TALON', 'TALON');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('705969', 'POMGFT', 'Pomegranate Gift');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706000', 'HAVAS', 'Havas Canada');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706167', 'ACADEM', 'ACADEMIQUE');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'ARSENL', 'Arsenal Pulp Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'ATLAS', 'ATLAS BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'AVEDIT', 'Avedition');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'BKMS', 'Bookmasters');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'BRAUN', 'Braun');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'DAAB', 'DAAB');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'DEABRN', 'DEARBORN PUBLISHING');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'ECW', 'ECW Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'FDLST', 'FEDERAL STREET');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'MARBAT', 'Mark Batty');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'RBNBR', 'Robin Brass');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'RCKPRT', 'ROCKPORT');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'RDBIRD', 'RED BIRD');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'REA', 'RESEARCH EDUCATION A');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'SELFCO', 'Self Council Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706365', 'WLTFST', 'WALTER FOSTER');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706570', 'EF', 'Easy Finder');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706570', 'ME', 'Map Easy');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706570', 'NG', 'National Georaphic');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706570', 'SF', 'Street Finder');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706646', 'ANNICK', 'ANNICK PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706646', 'BOSMIL', 'Boston Mills Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706646', 'FIRPAP', 'Firefly Paper');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706646', 'RROSE', 'ROBERT ROSE');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706646', 'SELFCO', 'SELF COUNCIL PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706646', 'WHTCAP', 'WHITECAP');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706647', 'COTEAU', 'Coteau Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706647', 'TRIFOL', 'Trifolium');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706678', 'PRSVTA', 'Prosveta Inc.');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706717', 'MGM', 'MGM');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706795', 'FRNWAT', 'Franklin Watts - Can');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706969', 'LYNX', 'LYNX IMAGES');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('706969', 'TRADE', 'N49 TRADE BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707015', 'DUMOAK', 'Dumbarton Oak');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707015', 'HOWUNV', 'Howard Univ Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707015', 'JHU', 'John Hopkins Univers');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707015', 'RFFI', 'Res. for the Future');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707016', 'CDG', 'CDG Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707016', 'GAGE', 'Gage Learning');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707107', 'SAUND', 'Saunders');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707120', 'LEMEAC', 'Lemeac');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707120', 'M.A.', 'M.A');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707147', 'ARCT', 'Arcturus Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707147', 'BRADY', 'Brady Games');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707147', 'DK', 'Dorling Kindersley L');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707147', 'EAMILL', 'Milley  Enterprise');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707147', 'KENS', 'Kensington Pub Corp');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707147', 'MINT', 'Mint Publishers Inc');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707147', 'NORTON', 'Norton');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707147', 'PENG', 'Penguin/Putnam');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707147', 'RW', 'Riverwood Publishers');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707147', 'TENSPD', 'Ten Speed Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707147', 'TSINTR', 'Ten Spd/Inner Tradit');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'ARCT', 'PENG ARCTURUS PUB');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'BRADY', 'PENG BRADY GAMES');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'CANDLE', 'Candlewick Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'CROWN', 'Crown Publishing Gro');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'DCCOMI', 'DC Comics');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'DK', 'PENG DK');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'EGMONT', 'EgmontUSA');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'FODORS', 'Fodor''s Guides (var)');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'HATHER', 'Hatherleigh Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'KENS', 'PENG KENSINGTON');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'KUPERA', 'Kuperard');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'M&S', 'McClelland & Stewart');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'MCCLEL', 'McClelland & Stewart');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'MELVIL', 'Melville House');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'NATGEO', 'National Geographic');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'NEWYOR', 'New York Review of B');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'NORTHA', 'North Atlantic Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'NORTON', 'PENG NORTON');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'OSPREY', 'Osprey Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'OTHERP', 'Other Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'PENG', 'PENGUIN/PUTNAM');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'RIZZOL', 'Rizzoli');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'SHAMBH', 'Shambhala');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'STEERF', 'Steerforth Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'TENSPD', 'TENSPD');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'TITAN', 'Titan');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'TRANSC', 'Transcontinental Boo');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'VERTIC', 'Vertical Inc');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'WELCOM', 'Welcome Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707148', 'WIZARD', 'Wizards of the Coast');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707154', 'ADD', 'Addison Wesley');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707154', 'GINN', 'Ginn Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707154', 'HED', 'HED Study Editions');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707154', 'HEINE', 'Heineman');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707154', 'MAXW', 'Maxwell MacMillan Co');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707158', 'CAL', 'California');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707158', 'PRINCT', 'PRINCETON UNIVERSITY');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707160', 'STNUNV', 'Stanford Univ Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707173', 'KLUTZ', 'KLUTZ');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707176', 'DMR', 'DMR');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707176', 'FIDES', 'Fides');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707176', 'FLAM', 'Flammarion');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707181', 'ACADEM', 'short disc');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707195', 'REIDMR', 'REIDMORE BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707202', '43', 'discount 43%');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707206', 'GETTY', 'GETTY PUBLICATIONS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'ALTA', 'Alta Book Centre');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'ANVIL', 'Anvil Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'APLAUS', 'Applause Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'APPLEW', 'Applewood Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'ASPASI', 'Aspasia Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'BALTRA', 'Baltray Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'BAYARD', 'Bayard Canada');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'BLACKR', 'Black Rose Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'BOOKPC', 'Book Publishing Comp');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'BREAKW', 'BREAKWATER');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'BRIDGT', 'Bridget Williams');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'BRISTO', 'Bristol Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'BRTLIB', 'British Library');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'BTWLIN', 'Between the Lines');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'CASLON', 'Caslon');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'CDNMUS', 'Cdn.  Museum of Nat.');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'CFUACS', 'Centre For Urban And');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'CNTEUR', 'Central European Uni');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'CNTURB', 'Centre For Urban & C');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'CODASA', 'CODASAT');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'CONTIN', 'Continuum');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'CORM', 'Cormorant Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'COUNCI', 'Council Oak');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'D&M', 'D&M');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'DIAMON', 'Diamond Mind');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'DUND', 'Dundurn Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'EDGAR', 'Edgar Kent');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'EDICAT', 'Edication Media Corp');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'G7BOOK', 'G7 Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'GCENTR', 'Guidance Centre');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'GOLDEN', 'Golden Dog Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'GPP', 'Great Plains');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'GSELNE', 'Goose Lane Ed.');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'GUERNI', 'Guernica Editions');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'HAWORT', 'Haworth Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'HERITA', 'HERITAGE HOUSE');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'HOUNSL', 'Hounslow Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'HSANAN', 'House of Anansi');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'ISSI', 'Issi');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'JGORDO', 'J.Gordon Shillingfor');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'JGSHIL', 'J. Gord. Shillingfor');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'JUMP', 'Jump Math');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'KAPKID', 'Kapablekidz');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'KIDSCN', 'Kids Can Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'KNOWLG', 'Knowledge Bureau Ltd');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'LOBSTR', 'Lobster Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'MCDONA', 'McDonald & Woodward');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'MCDWOO', 'Mcdonald & Woodward');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'MGILLI', 'McGilligan Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'MLTLIN', 'Multilingual Matters');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'MONTAG', 'La Montagne Secrete/');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'MULHIS', 'Multicultural Histor');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'NEWPRS', 'New Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'NEWSPU', 'NEW SOCIETY PUB');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'NOEXIT', 'No Exit Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'NTMUSE', 'National Museum Sci');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'ONTINS', 'Ont. Inst. for Studi');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'OOLICH', 'Oolichan Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'PENNUP', 'Penn State UP');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'PIPPIN', 'Pippin Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'PONTIF', 'Pontifical Inst Of M');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'PRCQUL', 'Porcupine Quill');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'QUILLD', 'Quill Driver Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'ROMUSE', 'Royal Ontario Museum');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'ROUSSN', 'Roussan Publishers');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'SCHLAM', 'School of Americ Res');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'SECMTN', 'Secret Mountain');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'SERAPH', 'Seraphim Editions');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'SIGNAT', 'Signature Editions');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'SIMPIE', 'Simon and Pierre');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'SISTVI', 'Sister Vision Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'SQRONE', 'Square One Publisher');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'SSTORY', 'Second Story Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'SUBWAY', 'Subway Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'SUMACH', 'Sumach Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'SVISIO', 'Sister Vision Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'TALON', 'Talon Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'TEACHC', 'Teacher''s College Pr');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'TENSPD', 'Tenspeed Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'THEY', 'Theytus Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'THOMPS', 'Thompson Educational');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'TSAR', 'Tsar Publications');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'TWIN', 'Twin Guinep Ltd');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'UBC', 'Univ of British Colu');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'UMANIT', 'University of Manito');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'UNEWMX', 'Univ New Mexico Pres');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'UOTTAW', 'University of Ottawa');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'UTP', 'UTP');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'UTPHED', 'UTP Higher Education');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'UTPSCH', 'University of Toront');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'VANWEL', 'Vanwell Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'WLU', 'Wilfrid Laurier Univ');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'WOLSAK', 'Wolsak & Wynn Pub');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707208', 'WTP', 'Winding Trail Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707220', 'CANWST', 'CanWest Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707220', 'COMAG', 'Comag Marketing Grp');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707220', 'D&M', 'Douglas & McIntyre');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707220', 'DORCH', 'Dorchester');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707220', 'HEARST', 'Hearst Book Group');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707220', 'HERITA', 'HERITAGE HOUSE');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707220', 'HSANAN', 'House of Anansi');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707220', 'MCARTH', 'Mcarthur & Co');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707220', 'NELSON', 'THOMAS NELSON');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707220', 'NEWSPU', 'NEW SOCIETY PUB');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707220', 'RUNGFT', 'Running Press Gift');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707220', 'TOKYOP', 'Tokyopop');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707220', 'ZONDER', 'Zondervan Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707251', 'NRTHST', 'Northstone Pub');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('707445', 'SRCPAP', 'Sourcebooks Paper');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('709690', 'ACTAR', 'ACTAR');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('709690', 'DOMED', 'DOM EDITIONS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('709690', 'GRAPHI', 'GRAPHIC BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('709690', 'OREIL', 'O''REILLY');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('709690', 'SPORTS', 'SPORTS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('709690', 'TASCHN', 'Taschen');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('709690', 'TAUNTN', 'TAUNTON BOOKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'ARCPUB', 'Arcade Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'BLKDOG', 'Black Dog');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'CASSEL', 'Cassell');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'CHRONI', 'Chronicle');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'CONRAN', 'Conran');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'DISNEY', 'Disney Book Group');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'FILIPA', 'Filipacchi');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'GAIA', 'Gaia');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'GAUDIO', 'Gildan Audio');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'GODSFL', 'Godsfield');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'HACCHI', 'Hachette Childrens');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'HAMLYN', 'Hamlyn');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'HARNAB', 'Harry N. Abrams');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'HBG', 'Hachette Proper');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'HEADLI', 'Headline');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'HODDER', 'Hodder');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'HUK', 'Hackette UK');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'KIDSCN', 'KIDS CAN PRESS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'LITBUK', '"Little, Brown UK"');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'LITTLE', '"Little, Brown and Co"');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'MARVEL', 'Marvel');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'MBEAZL', 'Mitchell Beazley');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'MCARTH', 'MCARTH');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'ORION', 'Orion');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'PETERS', 'Peterson''s');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'PHAIDO', 'Phaidon Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'QUERCU', 'Quercus');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'SPRUCE', 'Spruce');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('712507', 'WEINST', 'Weinstein Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('713342', 'ATLASB', 'AtlasBooks');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('716076', 'ACADEM', 'Scholarly/Reference');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'ACMRS', 'ACMRSP');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'ACMRSP', '*ACMRS Publ*');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'ALABAM', 'University Of Alabam');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'AMEPHI', 'american Philanthrop');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'AMERIC', 'AMEPHI');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'AMPPUB', 'National Catholic Bi');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'ARICRI', 'Critical Languages P');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'ARIZON', 'University of Arizon');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'ARKANS', 'UNIV OF ARKANSAS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'BAGWYN', 'ACMRSP');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'BAYEUX', 'BAYEUX');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'CRITIC', 'ARICRI');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'DALKEY', 'Dalkey Archieve Pres');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'DANA P', '*DANAPR*');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'DANAPR', 'Dana Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'EPIC', 'EPIC');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'FAITH', '*FAITHP*');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'FAITHP', 'Faith Publishing Ser');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'GALLAU', 'GALLAU');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'GETTY', '*GETTYP*');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'GETTYP', 'Getty Publications');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'GUERRA', 'GUERRA');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'HILLSD', 'AMPPUB');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'INTERC', 'ITCSTU');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'IOWAPR', 'University Of Iowa P');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'ISI B0', '*ISIBKS*');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'ISI BO', 'ISIBKS');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'ISIBKS', 'ISI Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'ISLAND', 'Island Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'ITCSTU', 'Intercollegiate Stud');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'LEFTCO', 'Left Coast Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'LEGACY', 'The Legacy Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'MAHVL', 'Mahvl Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'MICHIG', 'Michigan State Unive');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'MINHIS', 'Minnesota Historical');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'MINNES', 'University Of Minnes');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'NORILL', 'Northern Illinois Un');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'NOTRED', 'University of Notre');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'OHIOST', 'Ohio State Universit');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'OREGON', 'Oregon State Univers');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'PARKHU', 'Parkhurst Brothers P');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'PARMEN', 'Parmenides Publishin');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'PASSIO', 'Passionaries Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'PENULT', 'Penultimate Press In');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'REDHEN', 'Red Hen Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'RESEAR', '"Research Publishers,"');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'ROBERT', 'Roberts and Company');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'RUSSEL', 'RUSSELL SAGE');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'SCION', 'Scion Publishing Ltd');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'SIDEWA', 'Sidewalks Book Compa');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'SIGNAT', 'Signature Books');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'SSRCSC', 'Social Science Resea');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'STANFD', 'Stanford University');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'STAUGU', 'St. Augustine Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'STUDYM', 'Studymates Limited');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'SWEDEN', 'Swedenborg Foundatio');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'TEMPLE', 'Temple University Pr');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'TEMPLT', 'Templeton Press');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'TENNES', 'University of Tennes');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'TEXAST', 'Texas Tech Universit');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'UMICH', 'UNIV OF MICHIGAN');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'UNICOL', 'University Press of');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'UNIWIS', 'University of Wiscon');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'UTAHPR', 'University of Utah P');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'UTAHST', 'Utah State Universit');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'VUUITG', 'Vu Boekhandel/Uitgev');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'WESHOM', 'Westholme Publishing');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'WESVIR', 'West Virginia Univer');
INSERT [#stgTradeVendorsVSR]([SAPVendorId], [VSRCode], [VSRDescription]) VALUES('718995', 'WISCHI', 'Wisconsin Historical');

DELETE	dst
FROM	[dbo].[stgTradeVendorsVSR] dst
	LEFT JOIN [#stgTradeVendorsVSR] src ON dst.[SAPVendorId] = src.[SAPVendorId] AND dst.[VSRCode] = src.[VSRCode]
WHERE	src.[SAPVendorId] IS NULL;

UPDATE	dst
SET	[VSRDescription] = src.[VSRDescription]
FROM	[dbo].[stgTradeVendorsVSR] dst
JOIN	[#stgTradeVendorsVSR] src ON dst.[SAPVendorId] = src.[SAPVendorId] AND dst.[VSRCode] = src.[VSRCode]
WHERE	src.[VSRDescription] <> dst.[VSRDescription];

INSERT	[dbo].[stgTradeVendorsVSR] (
	[SAPVendorId], [VSRCode], [VSRDescription]
)
SELECT	src.[SAPVendorId], src.[VSRCode], src.[VSRDescription]
FROM	[#stgTradeVendorsVSR] src
	LEFT JOIN [dbo].[stgTradeVendorsVSR] dst ON dst.[SAPVendorId] = src.[SAPVendorId] AND dst.[VSRCode] = src.[VSRCode]
WHERE	dst.[SAPVendorId] IS NULL;

